namespace("Beetny.EQ2AA");
Beetny.EQ2AA.Constants = {};
Beetny.EQ2AA.Constants.TreeTabOrder = ["Tradeskill", "Archetype", "Class", "Shadows", "Heroic", "Prestige", "General", "Dragon"];
Beetny.EQ2AA.Constants.ClassNames = {
	0 : "Assassin",
	1 : "Berserker",
	2 : "Brigand",
	3 : "Bruiser",
	4 : "Coercer",
	5 : "Conjuror",
	6 : "Defiler",
	7 : "Dirge",
	8 : "Fury",
	9 : "Guardian",
	10 : "Illusionist",
	11 : "Inquisitor",
	12 : "Monk",
	13 : "Mystic",
	14 : "Necromancer",
	15 : "Paladin",
	16 : "Ranger",
	17 : "Shadowknight",
	18 : "Swashbuckler",
	19 : "Templar",
	20 : "Troubador",
	21 : "Warden",
	22 : "Warlock",
	23 : "Wizard",
	24 : "Beastlord",
	25 : "Channeler"
};

Beetny.EQ2AA.Constants.SortedClassNames = {
	"Assassin": 0,
	"Beastlord": 24,
	"Berserker": 1,
	"Brigand": 2,
	"Bruiser": 3,
	"Channeler": 25,
	"Coercer": 4,
	"Conjuror": 5,
	"Defiler": 6,
	"Dirge": 7,
	"Fury": 8,
	"Guardian": 9,
	"Illusionist": 10,
	"Inquisitor": 11,
	"Monk": 12,
	"Mystic": 13,
	"Necromancer": 14,
	"Paladin": 15,
	"Ranger": 16,
	"Shadowknight": 17,
	"Swashbuckler": 18,
	"Templar": 19,
	"Troubador": 20,
	"Warden": 21,
	"Warlock": 22,
	"Wizard": 23
};